# Generated by Django 4.2.27 on 2026-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_userprofile_department_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
