# Generated by Django 4.2.30 on 2026-04-21 12:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_incident_email_sent_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
