# Generated by Django 4.2.27 on 2026-05-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0023_contactmessage_is_read_contactmessage_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
